# Generated by Django 5.1.1 on 2024-09-29 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+\\d{1,3}\\d{9,15}$', message="Phone number must be entered in the format: '+919999999999'. Up to 15 digits allowed.")]),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='address',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+\\d{1,3}\\d{9,15}$', message="Phone number must be entered in the format: '+919999999999'. Up to 15 digits allowed.")]),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
