# Generated by Django 5.1.1 on 2024-09-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_app', '0004_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_description',
            field=models.TextField(default='Default Description', max_length=1000),
            preserve_default=False,
        ),
    ]
