# Generated by Django 5.1.1 on 2024-10-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_app', '0007_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(default='default description', max_length=1000),
            preserve_default=False,
        ),
    ]
