# Generated by Django 5.1.1 on 2024-10-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_app', '0011_document_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
