# Generated by Django 5.1.1 on 2024-10-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_app', '0012_remove_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(default='Default Document', max_length=100),
            preserve_default=False,
        ),
    ]
