# Generated by Django 5.1.1 on 2024-09-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_app', '0003_alter_case_client_alter_case_lawyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('brief', 'Brief'), ('contract', 'Contract'), ('memo', 'Memo')], max_length=100),
        ),
    ]
