# Generated by Django 5.1.1 on 2024-10-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_app', '0009_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gridfs_id',
            field=models.CharField(default='none', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
